// <auto-generated />
using System;
using AutomatedCodeGeneration.DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AutomatedCodeGeneration.DataLayer.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210224165142_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("AutomatedCodeGeneration.DataLayer.AccessModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.HasKey("Id");

                    b.ToTable("AccessModel");
                });

            modelBuilder.Entity("AutomatedCodeGeneration.DataLayer.Diagrams.ActorModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ActorModel");
                });

            modelBuilder.Entity("AutomatedCodeGeneration.DataLayer.Diagrams.ClassDiagram.ClassDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AccessId")
                        .HasColumnType("int");

                    b.Property<Guid?>("ClassModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("NameTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AccessId");

                    b.HasIndex("ClassModelId");

                    b.HasIndex("NameTypeId");

                    b.ToTable("ClassDataModel");
                });

            modelBuilder.Entity("AutomatedCodeGeneration.DataLayer.Diagrams.ClassDiagram.ClassMethodModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AccessId")
                        .HasColumnType("int");

                    b.Property<Guid?>("ClassModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("NameTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AccessId");

                    b.HasIndex("ClassModelId");

                    b.HasIndex("NameTypeId");

                    b.ToTable("ClassMethodModel");
                });

            modelBuilder.Entity("AutomatedCodeGeneration.DataLayer.Diagrams.ClassDiagram.ClassModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AccessId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SystemId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AccessId");

                    b.HasIndex("SystemId");

                    b.ToTable("ClassModel");
                });

            modelBuilder.Entity("AutomatedCodeGeneration.DataLayer.Diagrams.SystemModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("BeenGenerated")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Systems");
                });

            modelBuilder.Entity("AutomatedCodeGeneration.DataLayer.Diagrams.UseCaseModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FK_UseCase_Extends")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FK_UseCase_Includes")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SystemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("FK_UseCase_Extends");

                    b.HasIndex("FK_UseCase_Includes");

                    b.HasIndex("SystemId");

                    b.ToTable("UseCaseModel");
                });

            modelBuilder.Entity("AutomatedCodeGeneration.DataLayer.NameTypeModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClassMethodModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsStatic")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClassMethodModelId");

                    b.ToTable("NameTypeModel");
                });

            modelBuilder.Entity("AutomatedCodeGeneration.DataLayer.Diagrams.ClassDiagram.ClassDataModel", b =>
                {
                    b.HasOne("AutomatedCodeGeneration.DataLayer.AccessModel", "Access")
                        .WithMany()
                        .HasForeignKey("AccessId");

                    b.HasOne("AutomatedCodeGeneration.DataLayer.Diagrams.ClassDiagram.ClassModel", null)
                        .WithMany("Data")
                        .HasForeignKey("ClassModelId");

                    b.HasOne("AutomatedCodeGeneration.DataLayer.NameTypeModel", "NameType")
                        .WithMany()
                        .HasForeignKey("NameTypeId");

                    b.Navigation("Access");

                    b.Navigation("NameType");
                });

            modelBuilder.Entity("AutomatedCodeGeneration.DataLayer.Diagrams.ClassDiagram.ClassMethodModel", b =>
                {
                    b.HasOne("AutomatedCodeGeneration.DataLayer.AccessModel", "Access")
                        .WithMany()
                        .HasForeignKey("AccessId");

                    b.HasOne("AutomatedCodeGeneration.DataLayer.Diagrams.ClassDiagram.ClassModel", null)
                        .WithMany("Methods")
                        .HasForeignKey("ClassModelId");

                    b.HasOne("AutomatedCodeGeneration.DataLayer.NameTypeModel", "NameType")
                        .WithMany()
                        .HasForeignKey("NameTypeId");

                    b.Navigation("Access");

                    b.Navigation("NameType");
                });

            modelBuilder.Entity("AutomatedCodeGeneration.DataLayer.Diagrams.ClassDiagram.ClassModel", b =>
                {
                    b.HasOne("AutomatedCodeGeneration.DataLayer.AccessModel", "Access")
                        .WithMany()
                        .HasForeignKey("AccessId");

                    b.HasOne("AutomatedCodeGeneration.DataLayer.Diagrams.SystemModel", "System")
                        .WithMany("Classes")
                        .HasForeignKey("SystemId");

                    b.Navigation("Access");

                    b.Navigation("System");
                });

            modelBuilder.Entity("AutomatedCodeGeneration.DataLayer.Diagrams.UseCaseModel", b =>
                {
                    b.HasOne("AutomatedCodeGeneration.DataLayer.Diagrams.ActorModel", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorId");

                    b.HasOne("AutomatedCodeGeneration.DataLayer.Diagrams.UseCaseModel", "Extends")
                        .WithMany()
                        .HasForeignKey("FK_UseCase_Extends");

                    b.HasOne("AutomatedCodeGeneration.DataLayer.Diagrams.UseCaseModel", "Includes")
                        .WithMany()
                        .HasForeignKey("FK_UseCase_Includes");

                    b.HasOne("AutomatedCodeGeneration.DataLayer.Diagrams.SystemModel", "System")
                        .WithMany("UseCases")
                        .HasForeignKey("SystemId");

                    b.Navigation("Actor");

                    b.Navigation("Extends");

                    b.Navigation("Includes");

                    b.Navigation("System");
                });

            modelBuilder.Entity("AutomatedCodeGeneration.DataLayer.NameTypeModel", b =>
                {
                    b.HasOne("AutomatedCodeGeneration.DataLayer.Diagrams.ClassDiagram.ClassMethodModel", null)
                        .WithMany("Params")
                        .HasForeignKey("ClassMethodModelId");
                });

            modelBuilder.Entity("AutomatedCodeGeneration.DataLayer.Diagrams.ClassDiagram.ClassMethodModel", b =>
                {
                    b.Navigation("Params");
                });

            modelBuilder.Entity("AutomatedCodeGeneration.DataLayer.Diagrams.ClassDiagram.ClassModel", b =>
                {
                    b.Navigation("Data");

                    b.Navigation("Methods");
                });

            modelBuilder.Entity("AutomatedCodeGeneration.DataLayer.Diagrams.SystemModel", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("UseCases");
                });
#pragma warning restore 612, 618
        }
    }
}
